server:
  port: 8768
spring:
  application:
    name: stream1-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.100.23.92:9092
          auto-create-topics: true
      dynamic-destinations: stream-demo
      bindings:
        input:
          destination: stream-demo
          group: stream1
        output:
          destination: stream-demo-trans
eureka:
  #客户端
  client:
    #注册中心地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


