spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6h10w84d8f1wy4p7o.mysql.rds.aliyuncs.com:3306/security2?characterEncoding=UTF-8
    username: root
    password: Sink44253432
  application:
    name: shiro2-service
server:
  port: 5450
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:5450/oauth/check_token
