server:
  port: 8867
spring:
  application:
    name: elasticsearch-server
  data:
    elasticsearch:
      cluster-nodes: 139.224.233.92:9300
      cluster-name: docker-cluster
  elasticsearch:
    jest:
      uris: http://139.224.233.92:9200
management:
  health:
    elasticsearch:
      enabled: false