eureka:
  #客户端
  client:
    #注册中心地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 9001
spring:
  application:
    name: upload-server
