spring:
  application:
    name: sleuth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8833

logging:
  level:
    root: INFO
#    org.springframework.cloud: DEBUG
#    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org:
      springframework:
        cloud:
          sleuth: DEBUG
        web:
          servlet:
            DispatcherServlet: DEBUG
