server:
  port: 12000
  compression:
    enabled: false
spring:
  data:
    elasticsearch:
      cluster-nodes: 47.99.153.82:9300
      cluster-name: docker-cluster
  datasource:
    username: root
    password: Sink44253432
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6h10w84d8f1wy4p7o.mysql.rds.aliyuncs.com:3306/scrapy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  redis:
    host: 47.100.78.52
    port: 6379
    password: 44253432
management:
  health:
    elasticsearch:
      enabled: false

