server:
  port: 12001
  compression:
    enabled: false

spring:
  datasource:
    username: root
    password: Sink44253432
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6h10w84d8f1wy4p7o.mysql.rds.aliyuncs.com:3306/scrapy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
management:
  security:
    enabled: false
