server:
  port: 12000
  max-http-header-size: 8192
spring:
  data:
    mongodb:
      database: local
      password: 44253432
      host: 47.101.171.168
  redis:
    host: 139.224.233.92
    port: 6379

